# Generated by Django 4.1.3 on 2023-01-10 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
