# Generated by Django 4.1.3 on 2023-01-10 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reviews_carts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='data',
            new_name='date',
        ),
    ]
